Type this equation
and Give it a name called " Equation "


![alt text](https://latex.codecogs.com/gif.latex?%5Cfrac%7BX%5E%7B3%7D&plus;2X-0.5x%5E%7B-3%7D%7D%7BX%5E%7B2%7D&plus;2*10%5E%7B-5%7D%7D)

After Typing this pass a value 10 for X and Show the Result of this " Equation "

**Note** :
You might get an Error while typing the Equation !  Pass it!

In [1]:
#Type your Code here
# Define the equation function
def equation(X):
    numerator = X**3 + 2*X - 0.5*X**(-3)
    denominator = X**2 + 2*10**(-5)
    result = numerator / denominator
    return result


#Equation is function of x
x= 10
Equation = equation(x)
Equation
#Correct The Error
#Answer Should be 10.1999

10.199992960001408

Great! You should now understand the basics of variable assignment and reassignment in Python.


# Fix This Error On your Own

In [8]:
x= 50
y= 95
c=x # fix
z=y-c # fix
z += 5 # fix
z #Should Return 50

50

# 1. Numpy Scenario: **Population Statistics Analysis**

   Imagine you're a data analyst analyzing population statistics for different cities. Use NumPy to perform various calculations and manipulations on population data.

   a. Create a NumPy array representing the population of five cities: [1000000, 1200000, 800000, 1500000, 1100000].

   b. Calculate the mean, median, and standard deviation of the population data.

   c. Determine the index of the city with the highest population.

   d. Increase the population of each city by 10%.


In [10]:
### Sol of Scenario 1: Population Statistics Analysis

#a. **Create a NumPy array representing the population of five cities:**


import numpy as np

population = np.array([1000000, 1200000, 800000, 1500000, 1100000])
print("Population array:", population)

## continue here..

mean_population = np.mean(population)
median_population = np.median(population)
std_deviation = np.std(population)

print("Mean population:", mean_population)
print("Median population:", median_population)
print("Standard Deviation:", std_deviation)

# Determine the index of the city with the highest population
highest_population_index = np.argmax(population)
print("City with the highest population is at index:", highest_population_index)

# Increase the population of each city by 10%
population_data = population * 1.10

# Print the updated population data
print("Updated population data after a 10% increase:")
print(population)


Population array: [1000000 1200000  800000 1500000 1100000]
Mean population: 1120000.0
Median population: 1100000.0
Standard Deviation: 231516.7380558045
City with the highest population is at index: 3
Updated population data after a 10% increase:
[1000000 1200000  800000 1500000 1100000]


# 2.Numpy Scenario: **Financial Analysis**

   Assume you're working on financial data to analyze daily stock prices. Utilize NumPy to perform array operations and analysis.

   a. Create two NumPy arrays representing daily stock prices for a week for two different companies. You can use random data or invent your own.

   b. Calculate the daily returns for each company.

   c. Determine the days when the stock price of the first company was higher than the second company.

  


In [12]:
### Sol of Scenario 2: Financial Analysis

#a. **Create two NumPy arrays representing daily stock prices for a week for two different companies:**


import numpy as np

# Random daily stock prices for two companies for a week
company1_stock_prices = np.random.randint(50, 200, 7)  # Generate random data
company2_stock_prices = np.random.randint(50, 200, 7)  # Generate random data

print("Stock prices for Company 1:", company1_stock_prices)
print("Stock prices for Company 2:", company2_stock_prices)


## continue here..
# Calculate the daily returns for each company
company1_returns = (company1_stock_prices[1:] - company1_stock_prices[:-1]) / company1_stock_prices[:-1]
company2_returns = (company2_stock_prices[1:] - company2_stock_prices[:-1]) / company2_stock_prices[:-1]

# Determine the days when the stock price of the first company was higher than the second company
higher_price_days = np.where(company1_stock_prices > company2_stock_prices)[0]

print("Company 1 Daily Returns:")
print(company1_returns)

print("\nCompany 2 Daily Returns:")
print(company2_returns)

print("\nDays when Company 1 had a higher stock price than Company 2:")
print(higher_price_days)



Stock prices for Company 1: [178 199  64  96  66 175 174]
Stock prices for Company 2: [131  50  57  82 135 150 110]
Company 1 Daily Returns:
[ 0.11797753 -0.67839196  0.5        -0.3125      1.65151515 -0.00571429]

Company 2 Daily Returns:
[-0.61832061  0.14        0.43859649  0.64634146  0.11111111 -0.26666667]

Days when Company 1 had a higher stock price than Company 2:
[0 1 2 3 5 6]


# Pandas Scenario 1: **Data Analysis on Employee Information**
You have a dataset containing employee information. Let's create exercises based on this scenario.

* **a.Load the Dataset:**
Load the dataset named Employee_Salary_Dataset.csv into a Pandas DataFrame.
<br>#dataset Ref :https://www.kaggle.com/datasets/anninasimon/employee-salary-dataset
* **b.Display Basic Information:**
Display the first 10 rows, last 10 rows and the basic information (data types, non-null counts) of the DataFrame.

* **c.Calculate Statistics:**
Calculate the mean, median, and standard deviation of the 'Salary' column.

* **d.Filtering and Sorting:**
Filter the employees earning more than $80,000 and sort them in descending order of salary.

* **c.Grouping and Aggregation:**
Group the data by 'Department' and calculate the average salary for each department.

In [16]:
### Sol of Scenario 1: Data Analysis on Employee Information
import pandas as pd

# Load the dataset into a Pandas DataFrame

## continue here..
# Load the dataset into a Pandas DataFrame

file_path = r'C:\Users\morsh\Downloads\Employee_Salary_Dataset.csv'
df = pd.read_csv(file_path)

# a. Display the first 10 rows
print("First 10 rows:")
print(df.head(10))

# b. Display the last 10 rows
print("\nLast 10 rows:")
print(df.tail(10))

# Display basic information
print("\nBasic Information:")
df.info()

# c. Calculate mean, median, and standard deviation of the 'Salary' column
mean_salary = df['Salary'].mean()
median_salary = df['Salary'].median()
std_dev_salary = df['Salary'].std()

print("\nMean Salary:", mean_salary)
print("Median Salary:", median_salary)
print("Standard Deviation of Salary:", std_dev_salary)

# d. Filter employees earning more than $80,000 and sort them in descending order of salary
high_earning_employees = df[df['Salary'] > 80000]
sorted_high_earning_employees = high_earning_employees.sort_values(by='Salary', ascending=False)

print("\nEmployees earning more than $80,000, sorted by salary:")
print(sorted_high_earning_employees)

# e. Group the data by 'Department' and calculate the average salary for each department
department_avg_salary = df.groupby('Gender')['Salary'].mean()

print("\nAverage Salary by Department:")
print(department_avg_salary)


First 10 rows:
   ID  Experience_Years  Age  Gender   Salary
0   1                 5   28  Female   250000
1   2                 1   21    Male    50000
2   3                 3   23  Female   170000
3   4                 2   22    Male    25000
4   5                 1   17    Male    10000
5   6                25   62    Male  5001000
6   7                19   54  Female   800000
7   8                 2   21  Female     9000
8   9                10   36  Female    61500
9  10                15   54  Female   650000

Last 10 rows:
    ID  Experience_Years  Age  Gender    Salary
25  26                 3   22  Female     20000
26  27                 1   18    Male      3000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
29  30                 2   21  Female      6100
30  31                10   34    Male     80000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  F